### ISSUE TITLE
error

### ISSUE THREAD

**Issue by phillipbruh** [vanflux/google-snake-multiplayer-mod#4]
[GSM] Main error: Error: Linker no value found, detail: {"regex":"/\\{([\\w\\$]+):new [\\w\\$]+\\(Math\\.floor\\(3.*,[\\s\\r\\n\\t]*([\\w\\$]+):.*,[\\s\\r\\n\\t]*([\\w\\$]+):.*,[\\s\\r\\n\\t]*([\\w\\$]+):.*,[\\s\\r\\n\\t]*([\\w\\$]+):.*,[\\s\\r\\n\\t]*([\\w\\$]+):.*,[\\s\\r\\n\\t]*([\\w\\$]+):.*,[\\s\\r\\n\\t]*([\\w\\$]+):.*,[\\s\\r\\n\\t]*([\\w\\$]+):.*\\}/","expected":9,"type":"function"}
    at Object.findValues (gsm-mod.js:2:261656)
    at c.setup (gsm-mod.js:2:230658)
    at gsm-mod.js:2:243201
    at Object.<anonymous> (gsm-mod.js:2:243256)
    at Generator.next (<anonymous>)
    at gsm-mod.js:2:242254
    at new Promise (<anonymous>)
    at r (gsm-mod.js:2:241999)
    at t.pageLoadedEntry (gsm-mod.js:2:242605)
    at gsm-mod.js:2:310692

**Comment by EthanDawes** [comment]
I'm a little late, but for posterity, I believe it could be related to Google changing its code. [A bookmarklette approach is no longer possible](https://github.com/DarkSnakeGang/GoogleSnakeModLoader/blob/main/docs/why_not_bookmarks.md). I tried using [internet archive](https://web.archive.org/web/20221222083337/https://www.google.com/fbx?fbx=snake_arcade), but then got a different error that `e is not defined`.

**Comment by vanflux** [comment]
Yeah, days ago I saw that they changed the code a LOT

**Comment by Yarmiplay** [comment]
@vanflux any chance you'll help us revive this mod in 2025? we ((DarkSnakeGang)) have a consistent working version of the game at googlesnakemods.com and we'd love to add this mod and keep it updated on there, somehow, my discord is "yarmiplay"

**Comment by vanflux** [comment]
> [@vanflux](https://github.com/vanflux) any chance you'll help us revive this mod in 2025? we ((DarkSnakeGang)) have a consistent working version of the game at googlesnakemods.com and we'd love to add this mod and keep it updated on there, somehow, my discord is "yarmiplay"

Hi, I saw these versions a time ago, it is very nice to keep some mods working independently of google builds process. I can make progress on some of these versions, but there a loooot of rewrites to do again.
